services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    image: myapp_image:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
       RAILS_ENV: production
       DATABASE_URL: postgres://postgres:password@db:5432/app_production
       REDIS_URL: redis://redis:6379/0
       RAILS_LOG_TO_STDOUT: "true"
       RAILS_SERVE_STATIC_FILES: "true"
       RAILS_HOST: backend.aburahmah.com #need to make sure from domain
       RAILS_PROTOCOL: https
       RAILS_ASSUME_SSL: "false"
       RAILS_FORCE_SSL: "false"
       PORT: "9006"
       SECRET_KEY_BASE: 36aacb7954cb8b8cc8677cbe7d3251049defe1853f11718c17f635edc8171da2
    volumes:
      - storage:/app/storage
    ports:
      - "9006:9006"
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p ${PORT:-9006}"]
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:${PORT:-9006}/up || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  sidekiq:
    image: myapp_image:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/app_production
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: 36aacb7954cb8b8cc8677cbe7d3251049defe1853f11718c17f635edc8171da2
    volumes:
      - storage:/app/storage
    command: ["bundle", "exec", "sidekiq"]

volumes:
  postgres_data:
  storage:
